[versions]
agp = "9.0.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.12.3"
kotlin = "2.3.10"
composeBom = "2024.09.00"
appcompat = "1.6.1"
material = "1.10.0"

#Json
converterGson = "2.11.0"

#Image
coil = "2.6.0"

#lifecycle
lifecycleKtx = "2.10.0"

#Lottie
lottieCompose = "6.4.1"

#Navigation compose
navigationCompose = "2.9.7"
kotlinSerializationJson = "1.10.0"

#Hilt
hiltVersion = "2.59.1"
kspVersion = "2.3.5"

#Hilt navigation compose
hiltNavigationCompose = "1.3.0"
uiToolingPreview = "1.10.2"
uiTooling = "1.10.2"

#Paging
pagingVersion = "3.4.0"

#retrofit
retrofit = "3.0.0"
retrofitSerialization = "3.0.0"

okhttpVersion = "4.12.0"
loggingInterceptor = "4.12.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

#coil
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }


#Lottie
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }

#Hilt
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

#Lifecycle
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleKtx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleKtx" }


#Navigation Safe with kotlin serialization
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }


#KSP (Kotlin Symbol Processing) for Hilt
kotlin-android-ksp = { group = "com.google.devtools.ksp", name = "ksp", version.ref = "kspVersion" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltVersion" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uiToolingPreview" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }

#Paging
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "pagingVersion" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingVersion" }

#Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofitSerialization" }

#OkHttp to log network requests and responses
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version = "okhttpVersion" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }


#serialization
kotlin-serialization-json = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

#KSP (Kotlin Symbol Processing) for Hilt
kotlin-android-ksp = { id = "com.google.devtools.ksp", version.ref ="kspVersion" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref ="hiltVersion" }


